import { useState, useEffect } from 'react'
import { api } from '../utils/api'
import { timeAgo } from '../utils/formatters'

export default function Reports() {
  const [reports, setReports] = useState([])
  const [selected, setSelected] = useState(null)

  useEffect(() => {
    api.reports(10).then(r => {
      setReports(r)
      if (r.length) setSelected(r[0])
    }).catch(console.error)
  }, [])

  const typeColor = t =>
    t === 'Coin Analysis' ? '#00D4A8' :
    t === 'Market Overview' ? '#4C9BE8' : '#FFB830'

  return (
    <div>
      <div className="page-header">
        <h1>📝 AI Market Reports</h1>
        <p>Generated by local Mistral 7B GGUF · Coin analysis · Market overview · Signal explanations</p>
      </div>

      {reports.length === 0 ? (
        <div className="card" style={{ textAlign: 'center', padding: 48 }}>
          <div style={{ fontSize: '2rem', marginBottom: 12 }}>🤖</div>
          <div style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>
            No reports available yet. Run the pipeline to generate AI reports.
          </div>
          <div style={{ color: 'var(--text-muted)', fontSize: '0.75rem', marginTop: 8 }}>
            Reports are generated via the Mistral 7B local LLM after sufficient data is collected.
          </div>
        </div>
      ) : (
        <div className="grid-2" style={{ alignItems: 'start' }}>
          {/* Report list */}
          <div>
            <div className="section-title">Report History</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              {reports.map(r => (
                <div
                  key={r.id}
                  className="card"
                  style={{
                    cursor: 'pointer',
                    borderColor: selected?.id === r.id ? typeColor(r.report_type) : 'var(--border)',
                    background: selected?.id === r.id ? `${typeColor(r.report_type)}08` : 'var(--card)',
                  }}
                  onClick={() => setSelected(r)}
                >
                  <div className="flex justify-between items-center">
                    <div>
                      <div style={{ fontWeight: 600, color: 'var(--text)', fontSize: '0.85rem', marginBottom: 3 }}>
                        {r.coin || 'MARKET'} — {r.report_type}
                      </div>
                      <div style={{ fontSize: '0.68rem', color: 'var(--text-muted)' }}>
                        {r.model_used} · {timeAgo(r.generated_at)}
                      </div>
                    </div>
                    <span style={{
                      padding: '2px 8px', borderRadius: 10, fontSize: '0.65rem',
                      color: typeColor(r.report_type), background: `${typeColor(r.report_type)}15`,
                      border: `1px solid ${typeColor(r.report_type)}30`,
                    }}>
                      {r.report_type}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Report content */}
          <div>
            <div className="section-title">Report Content</div>
            {selected ? (
              <div className="card">
                <div className="flex justify-between items-center mb-12">
                  <div>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: '1rem', fontWeight: 700, color: typeColor(selected.report_type) }}>
                      {selected.coin || 'MARKET'} — {selected.report_type}
                    </div>
                    <div style={{ fontSize: '0.68rem', color: 'var(--text-muted)', marginTop: 3 }}>
                      {selected.model_used} · {timeAgo(selected.generated_at)}
                    </div>
                  </div>
                </div>
                <div style={{
                  background: 'var(--bg)',
                  border: '1px solid var(--border)',
                  borderLeft: `3px solid ${typeColor(selected.report_type)}`,
                  borderRadius: 8,
                  padding: '14px 16px',
                  fontFamily: 'var(--font-mono)',
                  fontSize: '0.75rem',
                  color: '#A0AABF',
                  lineHeight: 1.8,
                  whiteSpace: 'pre-wrap',
                  maxHeight: 480,
                  overflowY: 'auto',
                }}>
                  {selected.report_text || 'No content available.'}
                </div>
              </div>
            ) : (
              <div className="card" style={{ textAlign: 'center', padding: 40, color: 'var(--text-muted)' }}>
                Select a report
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}
