import streamlit as st
from reports.llm_report_generator import LLMReportGenerator
from database.connection import get_engine
from config.coins import TRACKED_COINS
import pandas as pd


def render():
    st.markdown("## 📝 AI Market Intelligence Reports")
    st.info("Reports are generated by the self-hosted Mistral 7B LLM via Ollama.")

    engine = get_engine()
    generator = LLMReportGenerator()

    col1, col2 = st.columns([2, 1])
    with col1:
        coin = st.selectbox("Coin to Analyze", list(TRACKED_COINS.keys()), key="rep_coin")
    with col2:
        report_type = st.selectbox("Report Type", ["Coin Analysis", "Market Overview", "Signal Explanation"], key="rep_type")

    if st.button("🤖 Generate Report"):
        with st.spinner("🤖 Mistral 7B is analyzing the data..."):
            if report_type == "Coin Analysis":
                try:
                    price_df = pd.read_sql(f"""SELECT close FROM price_data WHERE coin = '{coin}'
                        ORDER BY timestamp DESC LIMIT 2""", engine)
                    current_price = float(price_df.iloc[0]["close"]) if not price_df.empty else 0
                    prev_price = float(price_df.iloc[1]["close"]) if len(price_df) > 1 else current_price
                    change_24h = (current_price - prev_price) / max(prev_price, 1) * 100

                    sent_df = pd.read_sql(f"""SELECT avg_sentiment, sentiment_velocity FROM sentiment_aggregated
                        WHERE coin = '{coin}' AND window_size = '4h' ORDER BY window_start DESC LIMIT 1""", engine)
                    sentiment = float(sent_df.iloc[0]["avg_sentiment"]) if not sent_df.empty else 0.5

                    ind_df = pd.read_sql(f"""SELECT rsi, macd_signal FROM technical_indicators
                        WHERE coin = '{coin}' ORDER BY timestamp DESC LIMIT 1""", engine)

                    signal_df = pd.read_sql(f"""SELECT signal_type, confidence FROM signals
                        WHERE coin = '{coin}' ORDER BY generated_at DESC LIMIT 1""", engine)

                    fg_df = pd.read_sql("SELECT index_value, label FROM fear_greed_index ORDER BY timestamp DESC LIMIT 1", engine)

                    coin_data = {
                        "symbol": coin, "name": TRACKED_COINS[coin]["name"],
                        "price": f"{current_price:,.2f}",
                        "change_24h": f"{change_24h:.2f}",
                        "sentiment": f"{sentiment:.2f}",
                        "fear_greed": str(fg_df.iloc[0]["index_value"]) if not fg_df.empty else "N/A",
                        "rsi": f"{float(ind_df.iloc[0]['rsi']):.1f}" if not ind_df.empty else "N/A",
                        "macd_signal": f"{float(ind_df.iloc[0]['macd_signal']):.4f}" if not ind_df.empty else "N/A",
                        "signal": str(signal_df.iloc[0]["signal_type"]) if not signal_df.empty else "N/A",
                        "confidence": f"{float(signal_df.iloc[0]['confidence']):.0%}" if not signal_df.empty else "N/A",
                    }
                    report = generator.generate_coin_report(coin_data)
                except Exception as e:
                    st.error(f"Data fetch error: {e}")
                    report = generator.generate_coin_report({"symbol": coin, "name": TRACKED_COINS[coin]["name"]})

            elif report_type == "Market Overview":
                report = generator.generate_market_overview()
            else:
                sig_df = pd.read_sql(f"""SELECT coin, signal_type, confidence, reasoning
                    FROM signals WHERE coin = '{coin}' ORDER BY generated_at DESC LIMIT 1""", engine)
                if not sig_df.empty:
                    report = generator.generate_signal_explanation(sig_df.iloc[0].to_dict())
                else:
                    report = "No recent signal found for explanation."

            st.markdown(f"""
            <div style="background:#0E1117;border:1px solid #2D3445;border-radius:12px;padding:24px;
                        font-family:'Inter',sans-serif;line-height:1.7;color:#E8EAED;">
                {report.replace(chr(10), '<br/>')}
            </div>
            """, unsafe_allow_html=True)

    # Show historical reports
    st.markdown("---")
    st.markdown("### 📚 Historical Reports")
    try:
        hist_df = pd.read_sql("""
            SELECT coin, report_type, model_used, generated_at, LEFT(report_text, 200) as preview
            FROM market_reports ORDER BY generated_at DESC LIMIT 10
        """, engine)
        if not hist_df.empty:
            for _, r in hist_df.iterrows():
                with st.expander(f"📄 {r['coin'] or 'ALL'} — {r['report_type']} — {str(r['generated_at'])[:16]}"):
                    st.text(r["preview"] + "...")
    except Exception as e:
        st.error(f"Historical reports error: {e}")
